### DISCUSSION TITLE
What embedding model should be used with Ollama and PGVector?

### DISCUSSION THREAD

**Discussion by smitchell** [spring-projects/spring-ai#1160] [General]
My question is, what embedding model should I use for Ollama with PGVector? I'm getting the following error testing embedding for the first time. I believe PGVector is limited to 2096.

`Caused by: org.postgresql.util.PSQLException: ERROR: expected 1536 dimensions, not 4096`

This is my vector store. 

```
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
```

The code is straight out of a Josh Long video, except Josh uses OpenAI, and I'm using Ollama running the Llama3.1 model. I know from testing that I'm getting the OllamaEmbeddingModel by default, which uses Mistral. 

```
    public void embedListing(final Listing listing) {
        var document = new Document(
                listing.name() + " " + listing.description(),
                Map.of("id", listing.id(),
                        "name", listing.name(),
                        "description", listing.description(),
                        "listingUrl", listing.listingUrl(),
                ));
        var split = this.tokenTextSplitter
                .apply(List.of(document));
        vectorStore.add(split);
    }
```

My application properties include `spring.ai.ollama.embedding.enabled=true`. I presume the fix is to add `spring.ai.ollama.embedding.model` set to some value other than `mistral,' but I don't know what to set it to.

**Comment by smitchell** [comment]
This is solved. I had to do the following:

1) Specified the `all-minilm` embedding mode.

```
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.1:8b
      embedding:
        enabled: true
        model: all-minilm
    vectorstore:
      pgvector:
        index-type: hnsw
        dimensions: 384
        distance-type: cosine_distance
```

2) Regenerated the vector store to match the selected embedding model. I supposed I could have done an alter table.

```
CREATE TABLE IF NOT EXISTS public.vector_store
(
    id        uuid default uuid_generate_v4() not null
        primary key,
    content   text,
    metadata  json,
    embedding vector(384)
);
```
