### DISCUSSION TITLE
Resources exposed to the agent

### DISCUSSION THREAD

**Discussion by shahbour** [spring-projects/spring-ai#2865] [Q&A]
I am trying spring ai MCP server and client , tools are working perfectly and I am able to run the tool function by chatclient but if I ask any question about resources it seems client is not aware of them 

Is this missing at the current time or how can introduce my resources to the client

```
    mcp:
      client:
        toolcallback:
          enabled: true
        sse:
          connections:
            accounts-server:
              url: http://localhost:8081
```

```
    @Bean
    ChatClient chatClient(ChatClient.Builder builder,ToolCallbackProvider tools) {
        var system = """
                You are an AI powered assistant to help emplyee get information about accounts
                """;
        return builder
        .defaultSystem(system)
        .defaultTools(tools)
        .build();
    }
```

```
Server response with Protocol: 2024-11-05, Capabilities: ServerCapabilities[experimental=null, logging=LoggingCapabilities[], prompts=PromptCapabilities[listChanged=true], resources=ResourceCapabilities[subscribe=false, listChanged=true], tools=ToolCapabilities[listChanged=true]], Info: Implementation[name=accounts-server, version=1.0.0] and Instructions null
```

As you can see i am receiving from server Resources but it is not being introduced to model
