### DISCUSSION TITLE
How to customize `sseEndpoint` in `HttpClientSseClientTransport`?

### DISCUSSION THREAD

**Discussion by StrongManLi** [spring-projects/spring-ai#2987] [Q&A]
I'm trying to customize the `sseEndpoint` in `HttpClientSseClientTransport` to avoid the default `/sse` suffix, but I'm facing challenges. Here's my current configuration and issue:

#### **Configuration**
```yaml
mcp:
  client:
    sse:
      connections:
        server1:
          url: https://xx.cn/sse/ff
```

Issue
The framework automatically appends /sse to the configured URL, resulting in a request to https://xx.cn/sse/ff/sse, which is incorrect.

The HttpClientSseClientTransport constructor uses a default sseEndpoint value (/sse):
```java
HttpClientSseClientTransport(HttpClient httpClient, HttpRequest.Builder requestBuilder, String baseUri,
                             String sseEndpoint, ObjectMapper objectMapper) {
    // ...
    this.sseEndpoint = sseEndpoint;
}
```

Request
Is there a way to override the sseEndpoint without modifying the source code?
