### ISSUE TITLE
Support multiple models like DeepSeek and OpenAI at the same time in one application

### ISSUE THREAD

**Issue by sp213** [spring-projects/spring-ai#2221]
**Expected Behavior**

SpringAI could support both DeepSeek and OpenAI configurations at the same time in one application.

**Current Behavior**

I failed to find a way to support both models at the same time in SpringAI.

**Context**

For now, the DeepSeek is using the configuration defined by OpenAI, so there is a problem, if I want to integrate DeepSeek, then there's no configuration for OpenAI. Any possibilities that SpringAI can support both models at the same time, in this way, I can dynamically switch the model from OpenAI to DeepSeek per client's request.

**Comment by kevintsai1202** [comment]
Agree! Many tools are capable of utilizing multiple models simultaneously to address a process issue. In Spring AI, however, one can only accomplish such tasks through more low-level approaches. It would be highly beneficial for software development if there were a class that could easily interchange multiple sets of configurations.

**Comment by sp213** [comment]
Yes, I really need this feature. I do believe this is a real case for many Spring AI applications as well.

**Comment by FakeTrader** [comment]
i think you can follow the doc https://docs.spring.io/spring-ai/reference/api/chatclient.html#_create_a_chatclient_programmatically or create beans for each model

**Comment by liShuangQ** [comment]
I use oneAPI as a service, and then Spring AI uses the package of OpenAI. In this way, different models are utilized. I'm not sure if this is correct.
```java
this.chatClient.prompt(
                        new Prompt(
                                p,
                                OpenAiChatOptions.builder()
                                        .model("xxxx")
                                        .build()
                        )
                )
                .call()
                .content();
```

**Comment by markpollack** [comment]
I agree this is a gap.  The issue in the example form @FakeTrader is that the underlying chatmodels in this use case need to point to different openai api compatible URLs.

 I am looking to fix this for RC1 at least for OpenAI by letting users define multiple client endpoints in applicaton.yml via a map.

Also note, that there is a slippery slope with models that claim to be openai api compatible but then add extra fields to the json.  This is polluting the openai implementation, so I think we need to have a dedicated deepseek module.

**Comment by markpollack** [comment]
As a example of what I'm thinking

```
spring:
  ai:
    openai:
      models:
        enabled: true
        instances:
          gpt4:
            apiKey: "your-api-key-for-gpt4"
            baseUrl: "https://api.openai.com"
            organizationId: "your-org-id"
            chatProperties:
              options:
                model: "gpt-4"
                temperature: 0.7
          llama:
            apiKey: "your-api-key-for-llama"
            baseUrl: "https://your-custom-endpoint.com"
            chatProperties:
              options:
                model: "llama-70b"
                temperature: 0.5
```

and some basic usage (not chat client based, but you get the idea)

```
@Service
public class MyAIService {
    private final OpenAiChatModelRegistry modelRegistry;
    
    public MyAIService(OpenAiChatModelRegistry modelRegistry) {
        this.modelRegistry = modelRegistry;
    }
    
    public String generateWithGpt4(String prompt) {
        OpenAiChatModel gpt4Model = modelRegistry.getModel("gpt4");
        // Use the model
        return gpt4Model.generate(prompt).getResult().getOutput().getContent();
    }
    
    public String generateWithLlama(String prompt) {
        OpenAiChatModel llamaModel = modelRegistry.getModel("llama");
        // Use the model
        return llamaModel.generate(prompt).getResult().getOutput().getContent();
    }
}
```
