### ISSUE TITLE
Add MetadataFields auto configuration in AzureVectorStore

### ISSUE THREAD

**Issue by Giurzo** [spring-projects/spring-ai#2340]
**Expected Behavior**

Be able to create an AzureVectorStore with specified MetadataFields list in the configuration, like:
```yaml
spring:
  ai:
    vectorstore:
      azure:
        url: endpoint
        api-key: key
        metadata-fileds:
          - name: filterField
            fieldType: string
```

**Current Behavior**

Without specifying these MetadataFileds when creating the AzureVectorStore bean, it is not possible to filter a query by these fields, forcing the bean to be created manually (like [here](https://docs.spring.io/spring-ai/reference/api/vectordbs/azure.html#_sample_code)) without using the auto-configuration feature.
