### ISSUE TITLE
server.servlet.context-path not properly factoring into SSE MCP server path

### ISSUE THREAD

**Issue by jorge-trujillo** [spring-projects/spring-ai#2512]
Please do a quick search on GitHub issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
When using the MCP Server Starter, one of the supported protocols is SSE. If you are setting a custom context path using the property `server.servlet.context-path`, the relevant paths for MCP will change, but the path given when you look at the `/sse` endpoint will not. Therefore MCP clients will break. This was tested with Cursor MCP.

**Environment**
JVM: OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
Spring AI version: "1.0.0-M6" (Used BOM)

Application was written in Kotlin but that shouldn't be relevant here.

**Steps to reproduce**
- Create any MCP server application that uses SSE
- Connect it to an MCP client, should work fine (I used /sse as the path in Cursor)
- Set the `server.servlet.context-path`, say to "/v1"
- Attempt to update your setup in your MCP client, it will always fail

If you look at the output of the /sse endpoint, the reason is that the path provided by the endpoint is incorrect. It will match what you set in `spring.ai.mcp.server.sse-message-endpoint` but it will _not_ include the context path.

**Expected behavior**
In my opinion, this would be fixed if the endpoint that is returned in the call to the `/sse` endpoint also prepended the context path.

**Minimal Complete Reproducible example**
Please provide a failing test or a minimal complete verifiable example that reproduces the issue.
Bug reports that are reproducible will take priority in resolution over reports that are not reproducible.

**Comment by mlmw92** [comment]
Same problem

**Comment by rod2k2** [comment]
same problem, how to solve it if have to add server.servelt.context-path ?

**Comment by HollisChen1** [comment]
I think there should be a issue of org.springframework.ai.mcp.server.autoconfigure.McpWebMvcServerAutoConfiguration(the same as McpWebFluxServerAutoConfiguration)
by adding bean in our config class like
   @Bean
    public WebMvcSseServerTransportProvider webMvcSseServerTransportProvider(
            ObjectProvider<ObjectMapper> objectMapperProvider, McpServerProperties serverProperties) {
        ObjectMapper objectMapper = objectMapperProvider.getIfAvailable(ObjectMapper::new);
        return new **WebMvcSseServerTransportProvider(objectMapper,serverProperties.getBaseUrl(), serverProperties.getSseMessageEndpoint(), serverProperties.getSseEndpoint());**
    }


    @Bean
    public RouterFunction<ServerResponse> mvcMcpRouterFunction(WebMvcSseServerTransportProvider transportProvider) {
        return transportProvider.getRouterFunction();
    }

**Comment by GregoireW** [comment]
I will answer myself:  those beans are initialized with default configuration (base url and sseEndpoint (the  /sse )  )  a small change to add the 2 others parameter should fix the issue

https://github.com/spring-projects/spring-ai/blob/687dea52e0ccf5ffe70dfbf6a7aa248d28c01bdc/auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/main/java/org/springframework/ai/mcp/server/autoconfigure/McpWebMvcServerAutoConfiguration.java#L75

https://github.com/spring-projects/spring-ai/blob/687dea52e0ccf5ffe70dfbf6a7aa248d28c01bdc/auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/main/java/org/springframework/ai/mcp/server/autoconfigure/McpWebFluxServerAutoConfiguration.java#L80

**Comment by GregoireW** [comment]
looking for this issue, I found a related one: #2841

**Comment by weiwudu** [comment]
> [@HollisChen1](https://github.com/HollisChen1) you mention:
> 
> > make sure your servlet context path was added to spring.ai.mcp.server.base-url
> 
> But setting:
> 
> ```
> spring:
>   ai:
>     mcp:
>       server:
>         base-url: /myapp/
>         sse-endpoint: /sse
>         sse-message-endpoint: /mcp/message
> ```
> 
> on spring-ai 1.0.0-M7, I get on `curl http://localhost:8080/sse` a response containing: `data:/mcp/message?sessio...` so the base-url is not taken either I think

good job! This solution solved my problem

**Comment by mauricio1990silva** [comment]
has this been fixed? My mcp data endpoint is still going after /mcp/message as supposed to /api/mcp/message even though I have the base-url set to /api/

spring-ai 1.0.0-M7

**Comment by CloudSen** [comment]
Currently, I can only set the baseUrl to the context path.  
```
server:
  port: 8080
  servlet:
    context-path: /datakits/ai/web
spring:
  main:
    web-application-type: servlet
  ai:
    mcp:
      server:
        name: webmvc-mcp-server
        version: 1.0.0
        type: SYNC
        stdio: false
        instructions: "This server provides system current time tools"
        base-url: ${server.servlet.context-path}
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false
```
