### ISSUE TITLE
Document how to configure prompt and completion logging in the observability section

### ISSUE THREAD

**Issue by asaikali** [spring-projects/spring-ai#3127]
The docs at https://docs.spring.io/spring-ai/reference/observability/index.html don't explain that log levels on the observation handler need to be set to debug to see the completion and prompt show up in the logs. 

Example below shows the collection of settings needed to print out the chats and prompts. 

```yaml
spring:
   ai:
    chat:
      observations:
        log-prompt: true
        log-completion: true
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            observation: DEBUG
            client:
              observation: DEBUG
```

Example application at https://github.com/asaikali/spring-ai-zero-to-hero/tree/main/applications/provider-openai
