### ISSUE TITLE
Connect to the n8n MCP server using SSE.

### ISSUE THREAD

**Issue by An0nymous0** [spring-projects/spring-ai#3178]
Please do a quick search on GitHub issues first, the feature you are about to request might have already been requested.

**Expected Behavior**
## yaml config
```yaml
    mcp:
      client:
        toolcallback:
          enabled: true
        stdio:
          servers-configuration: classpath:mcp.json
        sse:
          connections:
            server1: http://localhost:5678/mcp/get_user_info/sse
```

## spring error
```
Factory method 'mcpSyncClients' threw exception with message: Failed to wait for the message endpoint
```
## n8n mcp server config

![Image](https://github.com/user-attachments/assets/98e37c87-21a3-4b85-8cdf-e750b0f2f730)

**Current Behavior**

Currently, it can only be accessed via stdio.

**Context**

**Comment by tzolov** [comment]
@An0nymous0 how to reproduce this issue. Is there a easy way to create n8n instance with mcp server

**Comment by An0nymous0** [comment]
> [@An0nymous0](https://github.com/An0nymous0) how to reproduce this issue. Is there a easy way to create n8n instance with mcp server

1. Visit this address (a simple example):

   https://n8n.io/workflows/3514-build-an-mcp-server-with-google-calendar-and-custom-functions/

2. Click on "Use Free."

3. Get started for free with n8n Cloud.

4. "My Functions Server" is an MCP server.

This will create an n8n MCP instance.

**Comment by denniskawurek** [comment]
Hi @tzolov ,
I saw this issue and was wondering whether this is related to the URI resolution problem as described here: https://github.com/modelcontextprotocol/java-sdk/issues/261
At least the error message indicates that the `closeLatch` in `HttpClientSseTransport` wasn't called, because of a failed connection attempt to the SSE endpoint.

**Comment by denniskawurek** [comment]
@An0nymous0 I re-checked this and asked myself if the format of your config is maybe wrong?


The [documentation](https://docs.spring.io/spring-ai/reference/api/mcp/mcp-client-boot-starter-docs.html#_sse_transport_properties) shows that it should be something like this:

```yml
        sse:
          connections:
            server1:
              url: http://localhost:5678
              sse-endpoint: /mcp/get_user_info/sse
```

Could you try this, please? Without warranty as there are few problems with URI resolutions in the underlying library.
