### ISSUE TITLE
Unable to disable Gemini and Vertex during testing

### ISSUE THREAD

**Issue by Alos** [spring-projects/spring-ai#3276]
**Bug description**
I'm unable to disable Vertex during testing. 

I get the folloing when running in a hermetic environment with no access to GCP:

```
Factory method 'connectionDetails' threw exception with message: Vertex AI project-id must be set!
```

I added the following to the `boostrap.properties`:

```
spring.ai.model.chat=none
spring.ai.vertex.ai.embedding.text=none
spring.ai.vertex.ai.embedding.multimodal=none
```

For good measure I also added it to my `application-test.yaml`

```YAML
spring:
  profiles:
    active: 'test'
  ai:
    model:
      chat: 'none'
    vertex:
      ai:
        embedding:
          text: 'none'
          multimodal: 'none'
```

**Environment**
spring-ai.version= 1.0.0
Java 24

**Steps to reproduce**
1. Create a new empty project with https://start.spring.io/
2. Add spring-ai-starter-model-vertex-ai-embedding and spring-ai-starter-model-vertex-ai-gemini
3. Try to disable them in your application.properties or YAML
4. Run the `contextLoads` test autogenerated by Spring.

**Expected behavior**
The tests pass.
