### ISSUE TITLE
Help me, my mcp tool doesn't work。I would be very grateful if anyone could help me。

### ISSUE THREAD

**Issue by qiuyueovo** [spring-projects/spring-ai#3291]
**Bug description**
Now it can be called successfully. But it will not call the tools in mcp。
What I can confirm is that there are tools in sse, and sse can be linked normally。
openAiClientManager is my custom built OpenAiChatModel and it works fine.
I have tried many methods and asked cursor. I have also read the relevant documents of springai, but I still can't find the reason for this problem. I have been troubled for 3 days. I would be very grateful if anyone could help me。

maven
```yml
  ai:
    mcp:
      client:
        enabled: true
        name: mcp-test-client
        version: 1.0.0
        request-timeout: 30s
        type: SYNC  # 同步客户端类型
        sse:
          connections:
            mcp-server: # MCP服务器连接名称
              url: http://0.0.0.0:3000
              sse-endpoint: /sse  # SSE端点
```

```     
<spring-ai.version>1.1.0-SNAPSHOT </spring-ai.version>
<dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-starter-mcp-client</artifactId>
            <version>${spring-ai.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-starter-model-openai</artifactId>
            <version>${spring-ai.version}</version>
        </dependency>
```

```java

    @Autowired
    List<McpSyncClient> mcpSyncClients;

    @Test
    public void predefinedQuestions() {
        HashSet<String> names = new HashSet<>();
        OpenAiChatModel client = openAiClientManager.getClient(OpenAiProvider.xxxx);
        for (McpSyncClient mcpClient : mcpSyncClients) {
            for (McpSchema.Tool tool : mcpClient.listTools().tools()) {
                String name = tool.name();
                String description = tool.description();
                //System.err.println("name：" + name);
                //System.err.println("description：" + description);
                names.add("mcp_test_client_mcp_server_" + name);
            }
        }


        var mcpToolProvider = new SyncMcpToolCallbackProvider(mcpSyncClients);
        ToolCallback[] toolCallbacks = mcpToolProvider.getToolCallbacks();
        ChatClient chatClient = ChatClient.builder(client).defaultToolCallbacks(mcpToolProvider).build();
        String userQuestion = """
                What tools are available?
                """;

        Prompt prompt = new Prompt(userQuestion, OpenAiChatOptions.builder()
                .model("gpt-4o") 
                .build());

        System.out.println("> USER: " + userQuestion);
        System.out.println("> ASSISTANT: " + chatClient.prompt(prompt).call().content());

    }
```

```java
    private OpenAiChatModel buildModel(OpenAiProvider provider) {
        OpenAiApi openAiApi = OpenAiApi.builder().apiKey(cfg.getApiKey()).baseUrl(cfg.getBaseUrl()).build();
        OpenAiChatModel chatModel = OpenAiChatModel.builder().openAiApi(openAiApi).build();
        return chatModel;
    }
```
