### ISSUE TITLE
OpenAI Transcription Options are Getting Overwritten

### ISSUE THREAD

**Issue by springframeworkguru** [spring-projects/spring-ai#648]
When using AudioTranscription Options, they seem to be getting overwritten with the defaults. 

Setting options as: 
```
OpenAiAudioTranscriptionOptions transcriptionOptions = OpenAiAudioTranscriptionOptions.builder()
                .withResponseFormat(OpenAiAudioApi.TranscriptResponseFormat.SRT)
                .withModel(OpenAiAudioApi.WhisperModel.WHISPER_1.name())
                .withTemperature(0f)
                .build();

        AudioTranscriptionPrompt prompt = new AudioTranscriptionPrompt(file.getResource(), transcriptionOptions);
 ```
Will always return text, response format is ignored. 

HOWEVER, 
Setting options at a global level via properties, this works. 

Example:
```
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      audio:
        transcription:
          options:
            response-format: srt
```
This will produce the srt output properly. Seems the options set via properties are overriding the options set in Java.

I saw this working okay before. I think this [commit](https://github.com/spring-projects/spring-ai/commit/df92dff36a1927ce5f4b11db4095266eceb07c9a#diff-a75e4909b19e6098e01eb7adc7b749c318191b51e00d4d04de1268d4f0404b7f) might be overriding the options.
