### ISSUE TITLE
PGVECTOR INDEX is created at each application startup

### ISSUE THREAD

**Issue by srssrs** [spring-projects/spring-ai#783]
**Bug description**
The pgvector index is created at each application startup if the `spring.ai.vectorstore.pgvector.index-type` property is other than NONE.  There should be a check that prevents creation if the index is already present. 

**Environment**
Spring AI version: 1.0.3 
Java version: 17
Vector store: pgvector 

Application properties configuration:
```yaml
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
```

**Steps to reproduce**
Start application and check the pgvector indexes. 
A new index is created at each restart. See attached figure.

**Expected behavior**
If the index already exists, it does not need to be created

<img width="416" alt="PgVectorIndex" src="https://github.com/spring-projects/spring-ai/assets/6746414/56e5ad3c-759e-43af-9d8a-4ab83c44d2d6">
